### ISSUE TITLE
I'm still a starter on everything and can't interpret that Error. :/

### ISSUE THREAD

**Issue by SirTommyMyers** [nbrette/twitter_giveaway_enterer#3]
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    enterer = Enterer(args.language, args.key)
  File "/home/sirscratch/Desktop/Projects/twitter_giveaway_enterer/twitter_enterer.py", line 12, in __init__
    config = utils.load_configfile(CONFIG_FILENAME)
  File "/home/sirscratch/Desktop/Projects/twitter_giveaway_enterer/utils.py", line 22, in load_configfile
    data = json.load(file)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 37 column 5 (char 671)

I used python3 main.py --language en --key bernardinho to start the script and I changed the config the way I was supposed to and also created a Twitter Dev acc and filled out all the API related stuff in the config. I installed the extra packages via pip and also have python3.8 (maybe the version is the issue?) As I said I can't fully interpret the error message and thus not continue. Waiting for an answer but not expecting it too soon :smiley:

**Comment by nbrette** [comment]
Hi,
This error seems to come from a wrong config file.
Can you please post the content of your config file here ? Make sure to remove your API key before you do so.
Can you tell me as well what the name of your config file is ?

**Comment by SirTommyMyers** [comment]
Here sir,

{
    "banned_users": [
        "bot",
        "spot",
        "lvbroadcasting",
        "jflessauSpam",
        "bryster125",
        "MobileTekReview",
        "ilove70315673",
        "followandrt2win",
        "traunte",
        "ericsonabby",
        "_aekkaphon",
        "korben"
    ],
    "banned_words": [
        "vote",
        "bot",
        "b0t",
        "discord",
        "join",
        "telegram",
        "youtube",
        "dm",
        "proofs",
        "proof",
        "pinned",
        "FB",
        "facebook",
        "yt",
        "twitch",
        "Screenshot",
        "fill out",
        "google form",
        "google forms",
        
    ],
    "research": {
        "fr": "concours",
        "en": "giveaway"
        

        
    },
    "tag_sentences": {
        "fr": [
            "A ne pas manquer ",
            "Intéressant ",
            "Pas mal ",
            "On va essayer de gagner ça ! ",
            "C'est parti ",
            "YOLO! ",
            "Peut-être que j’ai de la chance cette fois! ",
            "Essayons, je suppose. ",
            "Enfin un autre cadeau! "
            
        ],
        "en": [
            "Have a look a this ",
            "Check this out ",
            "Have a look bro ",
            "What about this ? ",
            "I hope I can win this ! ",
            "Let's try to win this ",
            "Lets go",
            "YOLO! ",
            "May I be lucky once xD ",
            "Let's give it a shot I guess ",
            "Yet another giveaway to ape into lmfao ",
            "Yo what do I see there! ",
            "Time for some gambling man! ",
            "Good to get another chance! ",
            "Finally a good giveway again! ",
            "Maybe we should yolo? ",
            "It's worth a shot ",
            "It's worth a try "
           
        ]
    },
    "tag_users": [
	"Sloww_loris", "Rachmandhika3", "AlekseiEvs", "MaraLaurao1", "chasngthedra8on", "Arash_1510", "itarik_1", "JDachor", "malayalipoli", "EA7HWS"

    ],
    "sol_address": "73fVYDf61tMgV4FUkd3HdkJ42zPRQ2xkDnYH7Rmr4n6w",
    "eth_address": "0xfBf277A6C5b6712F92c7c251C0112A7d50FEFcCb",
   
    "credentials": {
        "bernardinho":{
            "bearer_token": "",
            "consumer_key": "",
            "consumer_secret": "",
            "access_key": "",
            "access_secret": ""
        }
    }
}

The file is named config.json

**Comment by nbrette** [comment]
The format of your configuration file was incorrect.
You added elements in the `banned_words` array and left a trailing comma after the last element.

This is what you config file should look like:
```json
{
    "banned_users": [
    "bot",
    "spot",
    "lvbroadcasting",
    "jflessauSpam",
    "bryster125",
    "MobileTekReview",
    "ilove70315673",
    "followandrt2win",
    "traunte",
    "ericsonabby",
    "_aekkaphon",
    "korben"
    ],
    "banned_words": [
    "vote",
    "bot",
    "b0t",
    "discord",
    "join",
    "telegram",
    "youtube",
    "dm",
    "proofs",
    "proof",
    "pinned",
    "FB",
    "facebook",
    "yt",
    "twitch",
    "Screenshot",
    "fill out",
    "google form",
    "google forms"
],
    "research": {
        "fr": "concours",
        "en": "giveaway"
        
    
        
    },
    "tag_sentences": {
        "fr": [
            "A ne pas manquer ",
            "Intéressant ",
            "Pas mal ",
            "On va essayer de gagner ça ! ",
            "C'est parti ",
            "YOLO! ",
            "Peut-être que j’ai de la chance cette fois! ",
            "Essayons, je suppose. ",
            "Enfin un autre cadeau! "
            
        ],
        "en": [
            "Have a look a this ",
            "Check this out ",
            "Have a look bro ",
            "What about this ? ",
            "I hope I can win this ! ",
            "Let's try to win this ",
            "Lets go",
            "YOLO! ",
            "May I be lucky once xD ",
            "Let's give it a shot I guess ",
            "Yet another giveaway to ape into lmfao ",
            "Yo what do I see there! ",
            "Time for some gambling man! ",
            "Good to get another chance! ",
            "Finally a good giveway again! ",
            "Maybe we should yolo? ",
            "It's worth a shot ",
            "It's worth a try "
           
        ]
    },
    "tag_users": [
    "Sloww_loris", "Rachmandhika3", "AlekseiEvs", "MaraLaurao1", "chasngthedra8on", "Arash_1510", "itarik_1", "JDachor", "malayalipoli", "EA7HWS"
    
    ],
    "sol_address": "73fVYDf61tMgV4FUkd3HdkJ42zPRQ2xkDnYH7Rmr4n6w",
    "eth_address": "0xfBf277A6C5b6712F92c7c251C0112A7d50FEFcCb",
    
    "credentials": {
        "bernardinho":{
            "bearer_token": "",
            "consumer_key": "",
            "consumer_secret": "",
            "access_key": "",
            "access_secret": ""
        }
    }
}
```

This is very basic JSON, just use a json file validator to check if you are not comfortable with that.

**Comment by SirTommyMyers** [comment]
Yo thanks a lot the Script is 99% working now. The only issue left is the following response after each giveaway is presented in my cmd
Error code : {'response': <Response [403]>, 'api_errors': [], 'api_codes': [], 'api_messages': []}

Is it possible that I need the elevated access for the Twitter API? I'm currently waiting for validation on that but Twitter's answer is taking longer than expected. 
Another Issue connected to Error 403 (If Response 403 means that it's Errorcode 403) is the following that there appears to be a need for a SSL / HTTPS connection. The professional I am I have no real solution to that atm. You got any fix for that? 

In the meantime I'll be stepping down the rabbit hole furthermore and try to understand what exactly that type of connection etc is :) 

Also do you plan on integrating other wallet supports too? I tried to implement an ethereum wallet addon which I yet couldn't test but the more Wallets are supported the better innit? :P

**Comment by SirTommyMyers** [comment]
I'm an idiot. I just saw the other issue on this project and your answer. I'll try the given solution :)

**Comment by SirTommyMyers** [comment]
New Problem, I seem to have fixed the 403 error but now got the 401 error. If I'm correct that's due to no authorization which I tried to fix with auth0 to generate the needed credentials but with auth0 I'd need access to the elevated Twitter API. 

How do you usually turn on OAuth 1.0a and OAuth 2.0 while using the Twitter API v2 only? Thanks

**Comment by nbrette** [comment]
As you said 401 error is due to unauthorized access.
In the User authentication settings turn on OAuth 2.0 and OAuth 1a, select automated app for the type of app, read and write for the permission and put random url for the required field below.
Once you have done this go to the keys and token section of your app regenerate your access token and secret.
If you still have the 401 error after that, it just mean that you are using the wrong credentials in the config file.

The elevated access has nothing to do with all that and is required pretty much only to increase the request limit, which is useless because you will get banned before reaching the standard limit.

**Comment by SirTommyMyers** [comment]
That did the trick. I thought I'd need a big a** authentification process etc just to get access lmao. Didn't expect it to be that easy. Took the wrong + harder way. But now It's running. Last question, do you plan in implementing more wallets support or should I try adding for example the bnb wallet myself? :)

Have a nice day!

**Comment by nbrette** [comment]
Currently I don't have time to add features to the bot. I have noticed very few BNB giveaway anyway.
However adding any crypto would be pretty easy by doing the following steps:
- Make sure you add a bnb section in the config file and update the config reader 
- Add a bnb address attribute in the constructor of the class.
- Finally add a condition and the required words to detect a bnb giveaway in the function `tweet_action()`

Feel free to contribute to the project and make a PR.

**Comment by SirTommyMyers** [comment]
Thank you, I'll try it :D
