### ISSUE TITLE
Got myself wrecked

### ISSUE THREAD

**Issue by SirTommyMyers** [nbrette/twitter_giveaway_enterer#4]
Yo it's me again. I worked on getting new Wallet types into the script, I tried to fix the tag error and I also tried to automate the process of running the script every 16-21 minutes and expanded all the config files so twitter has a hard time noticing. But just as I was testing I got wrecked and suspended.

I think the issue was that I created some error in a loop or something that made the script pull the same tweets over and over again till I reached the rate limit and got instabanned. 

I'd just like to say I had quite some fun and learned a lot from this repository and I think I'll stop working on the Twitter Giveaway Bot Idea because the API is limited af and 99,99% of the giveaways are just Whitelists and OG roles on Crypto Discords and also fake so with the Twitter restrictions it's almost impossible to actually win something real because you need to enter like 200 giveaways for a win and then it's just a role on a discord. 

Also I ran into a little problem with the blacklisted words because it appears that even though I added for example WL or Whitelist to the list the script still pulled and worked with Tweets containing these words. I tried to find the reason but my knowledge is still too basic and my motivation faded instantly as my project was banned because I was like 99% done but can't test the code anymore.

This leads to the issue / my last question..

Can I just delete my project and create a new one within the Twitter API and am free to use everything again or continue or will this new project be monitored with special intensity and banned again if it's acting the same way as my first try? Will my account be banned if I have another restricted project?

Thank you very much for the repository and the opportunity to learn a lot about python :)

**Comment by nbrette** [comment]
Hello,

I haven't noticed anything wrong about banned words, but I don't have the time to check in details anyway.
As you said there are a lot of fake giveaways on twitter but are also a lot of real ones. I have ran the bot with mutiple accounts for a month and won over 150 giveways, clothes, tickets event and more than 120 NFTs as you can see on this opensea screenshot.
![nfts](https://user-images.githubusercontent.com/62093583/162133216-390a7d7a-ddab-4cfc-8ba7-4a270b3a0cef.png)

Regarding your question about twitter app, you can just delete the one that got banned and create a new one. I have noticed that once you get banned a couple of times you tend to get banned faster, but you can still work with the API without any problem if you don't abuse it.

**Comment by SirTommyMyers** [comment]
Thank you very much for the answer. I'll work on trying to find the issue with the banned words because 90% of the giveaways are WL spots which I don't need because I don't want to buy some random NFT xD And I'll work on new Twitter Apps etc but for the time I'm too busy :) I'll close this issue but I'll return sooner or later maybe with a pull req
