### ISSUE TITLE
Bot stops working

### ISSUE THREAD

**Issue by Miglekk** [nbrette/twitter_giveaway_enterer#5]
Hey! With little to no knowledge on python, I managed to config the bot following your tutorial. However, the bot stopped at the 4th or 5th giveaway with an error after it asked to tag 5 friends and I had only 2 on the list, so I added 3 more to the list and tried running the bot again, however this time, the bot runs and either it finds around 1 to 3 giveaways and stop or it finds none and stop, with no errors appearing.

**Comment by nbrette** [comment]
Hi,
Here is what the program does when you run it:
- It looks for the last 100 tweets posted containing the word "giveaway"
- For these 100 tweets it check multiple criterias like does it contain the word tag, rt, etc.
- If some of the tweet match the criterias then the giveaway is entered
- Once the last 100 tweets have been checked the program stops.

So when the program stops with no error it just means that it could not find any tweet matching the criterias. 
It is not got pull the new tweets by itself, so if you want it to run constantly you must use a crontab for example to schedule it !

**Comment by Miglekk** [comment]
> Hi, Here is what the program does when you run it:
> 
> * It looks for the last 100 tweets posted containing the word "giveaway"
> * For these 100 tweets it check multiple criterias like does it contain the word tag, rt, etc.
> * If some of the tweet match the criterias then the giveaway is entered
> * Once the last 100 tweets have been checked the program stops.
> 
> So when the program stops with no error it just means that it could not find any tweet matching the criterias. It is not got pull the new tweets by itself, so if you want it to run constantly you must use a crontab for example to schedule it !

I see, thanks for the explaining.     
Is there any way to increase that limit? I tried changing the "max_results=100" line but it does need a value between 10 and 100 so it didn't work.

**Comment by nbrette** [comment]
As you said the `search_recent_tweet()` function has a limit of 100 tweets for the result.
You could probably use the function `search_all_tweets` instead, it has a higher limit (up to 500). You'd probably want to use a date for the beggining and the end, and sort it by date. You can have a look a the documentation on this page:  
https://developer.twitter.com/en/docs/twitter-api/tweets/search/api-reference/get-tweets-search-all
However I don't know if i would impact the rest of the program. If the answer has the same format probably not, but I can't garantee it and don't have time to work on this project at the moment.

**Comment by Miglekk** [comment]
> As you said the `search_recent_tweet()` function has a limit of 100 tweets for the result. You could probably use the function `search_all_tweets` instead, it has a higher limit (up to 500). You'd probably want to use a date for the beggining and the end, and sort it by date. You can have a look a the documentation on this page: https://developer.twitter.com/en/docs/twitter-api/tweets/search/api-reference/get-tweets-search-all However I don't know if i would impact the rest of the program. If the answer has the same format probably not, but I can't garantee it and don't have time to work on this project at the moment.

I see. I'm going to try what you suggested and see if I can make it work. Thanks for the help!
